variable "name_prefix" {}
variable "env" {}
variable "vpc_id" {}
variable "public_alb_subnet_1a_id" {}
variable "public_alb_subnet_1b_id" {}
variable "private_container_subnet_1a_id" {}
variable "private_container_subnet_1b_id" {}
variable "private_rds_subnet_1a_id" {}
variable "private_rds_subnet_1b_id" {}
variable "igw_id" {}
variable "nat_gw_id" {}