variable "name_prefix" {}
variable "container_subnet_cidr_block_1a" {}
variable "container_subnet_cidr_block_1b" {}
variable "rds_subnet_cidr_block_1a" {}
variable "rds_subnet_cidr_block_1b" {}
variable "subnet_az_1a" {}
variable "subnet_az_1b" {}
variable "vpc_id" {}
variable "alb_subnet_cidr_block_1a" {}
variable "alb_subnet_cidr_block_1b" {}
variable "env" {}